import type { Role } from "@/app/types"

export const roles: Role[] = [
  {
    id: "frontend",
    title: "Frontend",
    description: "Interfaces and user experiences.",
    emoji: "🎨",
    categories: ["Client-side", "Design", "Product/UX"],
  },
  {
    id: "backend",
    title: "Backend",
    description: "Server logic, APIs, and databases.",
    emoji: "⚙️",
    categories: ["Server-side", "DevOps/Infra"],
  },
  {
    id: "fullstack",
    title: "Fullstack",
    description: "End-to-end application development.",
    emoji: "🌐",
    categories: ["Client-side", "Server-side", "DevOps/Infra"],
  },
  {
    id: "devops",
    title: "DevOps/Infra",
    description: "Deployment, scaling, and infrastructure.",
    emoji: "🔧",
    categories: ["DevOps/Infra", "Server-side"],
  },
  {
    id: "design",
    title: "Design/UX",
    description: "Visuals, branding, and user research.",
    emoji: "🎭",
    categories: ["Design", "Product/UX"],
  },
]

export const skillsByCategory: { [key: string]: string[] } = {
  "Client-side": [
    "React",
    "Vue.js",
    "Angular",
    "Svelte",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Sass/SCSS",
    "Webpack",
    "Vite",
    "Testing Library",
    "Cypress",
    "Jest",
  ],
  "Server-side": [
    "Node.js",
    "Python",
    "Java",
    "Go",
    "Rust",
    "PHP",
    "C#",
    "Ruby",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "REST APIs",
    "GraphQL",
    "Microservices",
    "Serverless",
  ],
  "DevOps/Infra": [
    "Docker",
    "Kubernetes",
    "AWS",
    "Google Cloud",
    "Azure",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "Linux",
    "Bash",
    "Nginx",
    "Apache",
    "Monitoring",
    "Logging",
  ],
  "Product/UX": [
    "Figma",
    "Adobe XD",
    "Sketch",
    "User Research",
    "Prototyping",
    "Wireframing",
    "A/B Testing",
    "Analytics",
    "Product Strategy",
    "Roadmapping",
    "Agile/Scrum",
    "Jira",
    "Confluence",
    "Miro",
    "FigJam",
    "Notion",
  ],
  Design: [
    "Photoshop",
    "Illustrator",
    "After Effects",
    "Figma",
    "Sketch",
    "InDesign",
    "Principle",
    "Framer",
    "Brand Design",
    "UI Design",
    "Icon Design",
    "Typography",
    "Color Theory",
    "Design Systems",
    "Motion Design",
    "3D Design",
  ],
}
